### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by cihadturhan** [arduano/Kiva#26]
I've been searching for a good midi editor/player app for mac os but couldn't find a good one.
Maybe Kiva can ba compiled for MacOS too?
Any possibility?

**Comment by arduano** [comment]
Kiva isn't an editor, and it's windows-only because it uses .NET framework and WPF. An alternative program that may work well for you is Wasabi, which is rust-based and cross-platform (Linux and Windows), and it will likely work on Mac, though we haven't tested.
https://github.com/arduano/wasabi

However, it's still technically in beta, and there's no builds. You'd need to build it yourself. To build, you need to install Cargo and the Vulkan SDK, and when you run it, you need to make sure to load a SFZ soundfont in the settings to get audio.

**Comment by cihadturhan** [comment]
Thank you! I’ll try it.

Cihad Turhan

On May 11, 2023, at 03:21, arduano ***@***.***> wrote:

﻿

Kiva isn't an editor, and it's windows-only because it uses .NET framework and WPF. An alternative program that may work well for you is Wasabi, which is rust-based and cross-platform (Linux and Windows), and it will likely work on Mac, though we haven't tested.
https://github.com/arduano/wasabi

However, it's still technically in beta, and there's no builds. You'd need to build it yourself. To build, you need to install Cargo and the Vulkan SDK, and when you run it, you need to make sure to load a SFZ soundfont in the settings to get audio.
