### ISSUE TITLE
VirusTotal is showing false positives, is this safe?

### ISSUE THREAD

**Issue by Sebastian150407** [arduano/Kiva#32]
So, today i wanted to download Kiva, but i wanted my PC to be safe, i analized the installer and it has: MaxSecure: Trojan.Malware.300983.susgen. McAfee Scanner: Ti!1FDBB1D4DF6B. And SecureAge: Malicious. And know i wonder, it is safe?

**Comment by Kaydax** [comment]
Its not a virus. The code is open source and the binaries provided on github are safe, and even virus total claims they are.

[Kiva.exe](https://www.virustotal.com/gui/file/c2e767393f3f2f6ecc4c229ac17a8415c51111acb3a41458e1cfc40fa19a07d8): 0 Found
[KivaInstaller.exe](https://www.virustotal.com/gui/file/1fdbb1d4df6b12fbd179a736a0ab1ac108ed5c16fa6146f76dec8ed2fc43ed49): 3 false positives due to it being an installer
